openapi: 3.0.0
info:
  title: API
  version: 2.0.0
  description: The main Node.js pipeline API.
  license:
    name: MIT
    url: 'https://github.com/hms-dbmi-cellenics/api/blob/master/LICENSE'
  contact:
    name: Biomage Ltd.
servers:
  - url: /v2
tags:
  - name: experiments
    description: Manage your experiments and experiment details.
  - name: heartbeat
    description: API health checks.
  - name: work
    description: Submitting and receiving work.
  - name: processing-config
    description: Structure for configuration of processing steps.
paths:
  /health:
    get:
      tags:
        - heartbeat
      summary: API health check
      operationId: checkHealth
      x-eov-operation-id: health#check
      x-eov-operation-handler: routes/health
      responses:
        '200':
          description: API is available.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    pattern: up
                  env:
                    type: string
                    enum:
                      - development
                      - test
                      - staging
                      - production
                  clusterEnv:
                    type: string
                    enum:
                      - development
                      - test
                      - staging
                      - production
                required:
                  - status
                  - env
                  - clusterEnv
      description: Returns a status on the health of the API.
  '/experiments':
    get:
      summary: Get all experiments
      description: Get all experiments that the user can access
      operationId: getAllExperiments
      x-eov-operation-id: experiment#getAllExperiments
      x-eov-operation-handler: routes/experiment
      responses:
        '200':
          description: All experiments that the user can acess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllExperiments'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  '/experiments/{experimentId}':
    get:
      summary: Get an experiment
      description: Get an experiment
      operationId: getExperiment
      x-eov-operation-id: experiment#getExperiment
      x-eov-operation-handler: routes/experiment
      responses:
        '200':
          description: Get experiment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExperimentInfo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
    post:
      summary: Create experiment
      description: Create a new experiment
      operationId: createExperiment
      x-eov-operation-id: experiment#createExperiment
      x-eov-operation-handler: routes/experiment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExperiment'
      responses:
        '200':
          description: Create experiment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
    patch:
      summary: Patch an experiment
      description: Update some properties in an experiment
      operationId: patchExperiment
      x-eov-operation-id: experiment#patchExperiment
      x-eov-operation-handler: routes/experiment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentPatch'
      responses:
        '200':
          description: Create experiment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  '/experiments/{experimentId}/samples/{sampleId}':
    post:
      summary: Create sample
      operationId: createSample
      x-eov-operation-id: sample#createSample
      x-eov-operation-handler: routes/sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSample'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
    delete:
      summary: Delete sample
      operationId: deleteSample
      x-eov-operation-id: sample#deleteSample
      x-eov-operation-handler: routes/sample
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  '/experiments/{experimentId}/samples/position':
    put:
      summary: Update position for a sample
      description: Set a new position for a sample
      operationId: updateSamplePosition
      x-eov-operation-id: experiment#updateSamplePosition
      x-eov-operation-handler: routes/experiment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPosition: 
                  type: integer
                newPosition:
                  type: integer
              required:
                - oldPosition
                - newPosition
              additionalProperties: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: The request lacks authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
components:
  schemas:
    CreateExperiment:
      $ref: './models/experiment-bodies/CreateExperiment.v2.yaml'
    ExperimentInfo:
      $ref: './models/experiment-bodies/ExperimentInfo.v2.yaml'
    ExperimentPatch:
      $ref: './models/experiment-bodies/ExperimentPatch.v2.yaml'
    GetAllExperiments:
      $ref: './models/experiment-bodies/GetAllExperiments.v2.yaml'
    CreateSample:
      $ref: './models/samples-bodies/CreateSample.v2.yaml'
    HTTPSuccess:
      $ref: './models/HTTPSuccess.v1.yaml'
    HTTPError:
      $ref: './models/HTTPError.v1.yaml'