apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/iac
---
apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
  annotations:
    filter.fluxcd.io/chart-image: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  chart: charts/nodejs
  interval: 2m0s
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v2/health
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml
  # filled in by CI. do not modify.
