apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/iac
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
  annotations:
    filter.fluxcd.io/chart-image: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: FILLED_IN_BY_CI
        namespace: FILLED_IN_BY_CI
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: "/v2/health"
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      namespace: FILLED_IN_BY_CI
      key: account-config.yaml
  # filled in by CI. do not modify.
