name: Pull Request Workflow
on:
  pull_request_review:
    types: [submitted]
  
# BEWARE: GitHub uses Microsoft-style line endings (CRLF)
# instead of Unix-style (LF) interally for things like PR text.
#
# You MUST check for `\r\n` as the line separator instead of `\n`
# in this workflow.
jobs:
  check-pr-template:
    if: github.event.review.state == 'approved'
    name: Check pull request template
    runs-on: ubuntu-20.04
    concurrency: 
      group: ${{ github.pull_request_review.pull_request.head.ref }}
      cancel-in-progress: true
    steps:
      - id: install
        name: Install requirements
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y pcregrep

      - id: check-jira-url
        name: Check JIRA URL
        run: |-
          REGEX="#### URL to JIRA issue\s?\r\n(https:\/\/biomage\.atlassian\.net\/browse\/BIOMAGE-[0-9]+|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request_review.pull_request.body }}
          EOF

      - id: extract-staging
        name: Check staging URL
        run: |-
          REGEX="#### Link to staging deployment URL\s?\r\n(https:\/\/ui-(.+)\.scp-staging\.biomage\.net|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          URL=$(pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request_review.pull_request.body }}
          EOF
          )

          SANDBOX=$(pcregrep -o2 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request_review.pull_request.body }}
          EOF
          )

          echo "Full URL:"
          echo $URL
          echo "::set-output name=url::$URL"

          echo "Sandbox:"
          echo $SANDBOX
          echo "::set-output name=sandbox::$SANDBOX"

          echo "SHA of PR:"
          echo $GITHUB_SHA
          echo "::set-output name=github_sha::$GITHUB_SHA"

          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')
          echo "Repo name:"
          echo $REPO_NAME
          echo "::set-output name=repo_name::$REPO_NAME"

      - id: extract-integration-test-ref
        name: Get integration test ref
        run: |-
          REGEX="#### Integration test branch\s?\r\n(.+)\s?\r\n"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          INTEGRATION_TEST_REF=$(pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request_review.pull_request.body }}
          EOF
          )

          echo "Ref given is $INTEGRATION_TEST_REF, setting it as is."
          echo "::set-output name=ref::$INTEGRATION_TEST_REF"

      - id: reach-staging
        name: Attempt to reach staging environments
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_on: error
          command: curl -f ${{ steps.extract-staging.outputs.url }}
          # Add jitter to break up correlated events.
          on_retry_command: sleep $(shuf -i 10-15 -n 1)s

      - id: run-integration-test
        name: Run integration tests
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Run end-to-end tests
          repo: biomage-ltd/testing
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: ${{ steps.extract-integration-test-ref.outputs.ref }}
          inputs: '{ "environment": "staging", "ref": "${{ steps.extract-integration-test-ref.outputs.ref }}", "sandboxId": "${{ steps.extract-staging.outputs.sandbox }}", "image_sha" : "${{ steps.extract-staging.outputs.github_sha }}", "namespace": "${{ steps.extract-staging.outputs.repo_name }}-${{ steps.extract-staging.outputs.sandbox }}" }'