name: Pull Request Workflow
on:
  pull_request:
    types: [ opened, reopened, edited ]
jobs:
  check-pr-template:
    name: Check pull request template
    runs-on: ubuntu-20.04
    steps:
      - id: check-jira-url
        name: Check JIRA URL
        run: |-
          apt-get update -y
          apt-get install -y pcregrep

          {
            ${{ github.event.pull_request.body }}
          EOF
          } 2> /dev/null | tee pr_body.md

          cat pr_body.md

          # JIRA_REGEX="#### URL to JIRA issue\n(https:\/\/biomage\.atlassian\.net\/browse\/BIOMAGE-[0-9]+|N\/A)$"ech
          # echo "" | pcregrep -M $JIRA_REGEX
