name: Pull Request Workflow
on:
  pull_request:
    types: [ opened, reopened, edited ]
jobs:
  
  # BEWARE: GitHub uses Microsoft-style line endings (CRLF)
  # instead of Unix-style (LF) interally for things like PR text.
  #
  # You MUST check for `\r\n` as the line separator instead of `\n`
  # in this workflow.
  check-pr-template:
    name: Check pull request template
    runs-on: ubuntu-20.04
    steps:
      - id: copy-pr-body
        name: Copy PR body to file
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y pcregrep

      - id: check-jira-url
        name: Check JIRA URL
        run: |-
          REGEX="#### URL to JIRA issue\s?\r\n(https:\/\/biomage\.atlassian\.net\/browse\/BIOMAGE-[0-9]+|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request.body }}
          EOF

      - id: check-staging-url
        name: Check staging URL
        run: |-
          REGEX="#### Link to staging deployment URL\s?\r\n(https:\/\/.+\.scp-staging\.biomage\.net|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request.body }}
          EOF