name: Pull Request Workflow
on:
  pull_request:
    types: [ opened, reopened, edited ]
jobs:
  
  # BEWARE: GitHub uses Microsoft-style line endings (CRLF)
  # instead of Unix-style (LF) interally for things like PR text.
  #
  # You MUST check for `\r\n` as the line separator instead of `\n`
  # in this workflow.
  check-pr-template:
    name: Check pull request template
    runs-on: ubuntu-20.04
    steps:
      - id: install
        name: Install requirements
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y pcregrep

      - id: check-jira-url
        name: Check JIRA URL
        run: |-
          REGEX="#### URL to JIRA issue\s?\r\n(https:\/\/biomage\.atlassian\.net\/browse\/BIOMAGE-[0-9]+|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request.body }}
          EOF

      - id: extract-staging
        name: Check staging URL
        run: |-
          REGEX="#### Link to staging deployment URL\s?\r\n(https:\/\/ui-(.+)\.scp-staging\.biomage\.net|N\/A)"

          echo "REGEX to test against:"
          echo $REGEX
          echo "Now looking at regex result:"

          URL=$(pcregrep -o1 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request.body }}
          EOF
          )

          SANDBOX=$(pcregrep -o2 -M "$REGEX" <<\EOF
          ${{ github.event.pull_request.body }}
          EOF
          )

          echo "Full URL:"
          echo $URL
          echo "::set-output name=url::$URL"

          echo "Sandbox:"
          echo $SANDBOX
          echo "::set-output name=sandbox::$SANDBOX"

      - id: reach-staging
        name: Attempt to reach staging environments
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_on: error
          command: curl -f ${{ steps.extract-staging.outputs.url }}
          # Add jitter to break up correlated events.
          on_retry_command: sleep $[($RANDOM % 10) + 5]s